CREATE TABLE IF NOT EXISTS {{params.db_name}}.{{params.schema_name}}.CUSTOMERS(
	ID NUMBER(38,0) NOT NULL,
	CUSTOMER_FIRST_NAME VARCHAR(256),
	CUSTOMER_MIDDLE_NAME VARCHAR(256),
	CUSTOMER_LAST_NAME VARCHAR(256),
	CUSTOMER_ADDRESS VARCHAR(256),
	primary key (ID)
);